[features]
seeds = false
skip-lint = false

[programs.devnet]
resynth = "synttWtyx32zPvSm7gioaHUGJ4ZFsZUmnviEvjtoyoa"
pyth = "HVKkrPBatCq4KkEo2j92o273xTw596hhUoFsMNnNbUfM"
token_faucet = "73ZZXhTSpH2nrm347fzoaRcjyCuMJ3u4jPq9jsrotin2"
token_swap = "swapuaCjB4Esqxk3P4Lq9HoHebe7Jj3q8hCe1j5bcay"

[programs.localnet]
resynth = "synttWtyx32zPvSm7gioaHUGJ4ZFsZUmnviEvjtoyoa"
pyth = "HVKkrPBatCq4KkEo2j92o273xTw596hhUoFsMNnNbUfM"
token_faucet = "73ZZXhTSpH2nrm347fzoaRcjyCuMJ3u4jPq9jsrotin2"
token_swap = "swapuaCjB4Esqxk3P4Lq9HoHebe7Jj3q8hCe1j5bcay"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "sdk/src/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[[test.validator.account]]
address = "9QhFb6usvzYXYNJtKqE1vzCemWVtpNCUmDSVZ66cJeYM"
filename = "./tests/accounts/faucet.json"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./tests/accounts/mint.json"

[[test.validator.account]]
address = "BynJzBW8CjEn4F1cwcR8mHrCSgfFHgGZfWpJMcmkGPi7"
filename = "./tests/accounts/oracle.json"
