[features]
seeds = false
skip-lint = false

[programs.devnet]
synth_amm = "EMA4zANmhMuSUqRqj3wNvAkGwRGXLJk7WpXQdW7bSwX1"
pyth = "HVKkrPBatCq4KkEo2j92o273xTw596hhUoFsMNnNbUfM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/wallet.json"

[workspace]
types = "tests/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
