[features]
seeds = false
skip-lint = false

[programs.localnet]
resynth = "BWxFf9EizbS1hxKPKJguxmvvxSggaVNK6V3TogPhuzAs"
pyth = "HVKkrPBatCq4KkEo2j92o273xTw596hhUoFsMNnNbUfM"
token_faucet = "73ZZXhTSpH2nrm347fzoaRcjyCuMJ3u4jPq9jsrotin2"
token_swap = "85aooyAumUJKEfcw84mnacWKGN5dTqb4EX5YQRp5SuLX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "sdk/src/idl/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
